List<Map> travel_spots = [
  {"img": "assets/mbti/ENFJ.png", "name": "ENFJ", "category": "1"},
  {"img": "assets/mbti/ENFP.png", "name": "ENFP", "category": "2"},
  {"img": "assets/mbti/ENTJ.png", "name": "ENTJ", "category": "3"},
  {"img": "assets/mbti/ENTP.png", "name": "ENTP", "category": "4"},
  {"img": "assets/mbti/ESFJ.png", "name": "ESFJ", "category": "5"},
  {"img": "assets/mbti/ESFP.png", "name": "ESFP", "category": "6"},
  {"img": "assets/mbti/ISTP.png", "name": "ISTP", "category": "7"},
  {"img": "assets/mbti/ISTJ.png", "name": "ISTJ", "category": "8"},
  {"img": "assets/mbti/ISFP.png", "name": "ISFP", "category": "9"},
  {"img": "assets/mbti/ISFJ.png", "name": "ISFJ", "category": "10"},
  {"img": "assets/mbti/INTJ.png", "name": "INTJ", "category": "11"},
  {"img": "assets/mbti/INTP.png", "name": "INTP", "category": "12"},
  {"img": "assets/mbti/INFP.png", "name": "INFP", "category": "13"},
  {"img": "assets/mbti/INFJ.png", "name": "INFJ", "category": "14"},
  {"img": "assets/mbti/ESTP.png", "name": "ESTP", "category": "15"},
  {"img": "assets/mbti/ESTJ.png", "name": "ESTJ", "category": "16"},
  {"img": "assets/mbti/ALL.png", "name": "ALL", "category": "17"},
];
